name: cifar10
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - pip>=19.0
  - typer>=0.9.0
  - requests=2.28.2
  - tensorflow-deps=2.10.0
  - pandas=2.0.0
  - pip:
    - tensorflow-macos==2.12.0
    - tensorflow-metal==0.8.0
    - streamlit==1.24.1
    - pydot==1.4.2
